services:
  # MySQL
  mysql-server:
    image: mysql:9 # https://hub.docker.com/_/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_secret_password}
      MYSQL_DATABASE: default_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: my_secret_password
      TZ: Asia/Shanghai # 设置时区
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./sql/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初始化数据库脚本
      # - ./sql/mysql/sql:/opt/sql  # 初始化数据库脚本

  # Redis
  redis-server:
    image: redis:7 # https://hub.docker.com/_/redis
    ports:
      - "6379:6379"
    networks:
      - default
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s # 等待 Redis 启动完成
      
# -- 网络名称，用于容器间通信
networks:
  default:
    name: hello-middleware-network

# -- 数据卷名称，用于持久化数据
volumes:
  mysql_data:
  elasticsearch_data: